from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.admin_home, name='admin_home'),
    path('portfolio/', views.admin_portfolio, name='admin_portfolio'),
    path('portfolio/edit/<int:pk>/', views.admin_portfolio, name='edit_portfolio'),
    path('custom-admin/portfolio/delete/<int:pk>/', views.delete_portfolio, name='delete_portfolio'),
    path('custom-admin/gallery/', views.admin_gallery, name='admin_gallery'),
    path('custom-admin/gallery/edit/<int:pk>/', views.admin_gallery, name='edit_gallery'),
    path('custom-admin/gallery/delete/<int:pk>/', views.delete_gallery, name='delete_gallery'),
    path('admin/team/', views.team_admin, name='team_admin'),
    path('admin/team/edit/<int:pk>/', views.edit_team, name='edit_team'),
    path('admin/team/delete/<int:pk>/', views.delete_team, name='delete_team'),
    path('custom-admin/careers/', views.admin_careers, name='admin_careers'),
    path('custom-admin/careers/edit/<int:pk>/', views.admin_careers, name='edit_job'),
    path('custom-admin/careers/delete/<int:pk>/', views.delete_job, name='delete_job'),
    path('custom-admin/facilities/', views.admin_facilities, name='admin_facilities'),
    path('custom-admin/facilities/edit/<int:pk>/', views.admin_facilities, name='edit_facility'),
    path('custom-admin/facilities/delete/<int:pk>/', views.delete_facility, name='delete_facility'),
    path('custom-admin/blog/', views.admin_blog, name='admin_blog'),
    path('custom-admin/blog/edit/<int:pk>/', views.admin_blog, name='edit_blog'),
    path('custom-admin/blog/delete/<int:pk>/', views.delete_blog, name='delete_blog'),
    path('custom-admin/faq/', views.admin_faq, name='admin_faq'),
    path('custom-admin/faq/edit/<int:pk>/', views.admin_faq, name='edit_faq'),
    path('custom-admin/faq/delete/<int:pk>/', views.delete_faq, name='delete_faq'),
    path('custom-admin/terms/', views.admin_terms, name='admin_terms'),
    path('custom-admin/terms/edit/<int:pk>/', views.admin_terms, name='edit_term'),
    path('custom-admin/terms/delete/<int:pk>/', views.delete_term, name='delete_term'),
    
    path('custom-admin/privacy/', views.admin_privacy, name='admin_privacy'),
    path('custom-admin/privacy/edit/<int:pk>/', views.admin_privacy, name='edit_privacy'),
    path('custom-admin/privacy/delete/<int:pk>/', views.delete_privacy, name='delete_privacy'),
    path('custom-admin/featured/', views.manage_featured, name='manage_featured'),
    path('custom-admin/featured/edit/<int:pk>/', views.manage_featured, name='edit_featured'),
    path('custom-admin/featured/delete/<int:pk>/', views.delete_featured, name='delete_featured'),
    path('custom-admin/featured/', views.manage_featured, name='manage_featured'),
    path('custom-admin/featured/edit/<int:pk>/', views.manage_featured, name='edit_featured'),
    path('custom-admin/featured/delete/<int:pk>/', views.delete_featured, name='delete_featured'),
    path('custom-admin/testimonials/', views.admin_testimonials, name='admin_testimonials'),
    path('custom-admin/testimonials/edit/<int:pk>/', views.admin_testimonials, name='edit_testimonial'),
    path('custom-admin/testimonials/delete/<int:pk>/', views.delete_testimonial, name='delete_testimonial'),
    path('custom-admin/bookings/', views.admin_bookings, name='admin_booking'),
    path('custom-admin/bookings/delete/<int:pk>/', views.delete_booking, name='delete_booking'),
    path('custom-admin/inquiry/', views.admin_inquiry, name='admin_inquiry'),
    path('custom-admin/inquiry/delete/<int:pk>/', views.delete_inquiry, name='delete_inquiry'),
    
]
